#!/usr/bin/env bash
# ============================================================
# DRIVELOG — BUILD SCRIPT
# ------------------------------------------------------------
# Run this EVERY time you edit any file in js/, db.js, data.js,
# or main.css, BEFORE pushing to GitHub. It:
#   1. Concatenates all files in js/ (in the fixed order below)
#      into one app.combined.js — same global-scope behavior as
#      the old single app.js, just split across readable files
#      for editing. No ES modules, no bundler magic: this is a
#      plain textual concatenation, so nothing about how the
#      site *runs* changes.
#   2. Re-minifies app.combined.js, db.js, data.js, and main.css
#      with esbuild (a real AST-based minifier — safe for URLs
#      inside strings, never reorders CSS rules or breaks
#      @media blocks)
#   3. Verifies the minified JS is valid syntax
#   4. Bumps the ?v= cache-busting version in index.html so
#      browsers fetch the new files (the .min files are cached
#      for 1 year by vercel.json — the version bump is what
#      forces the refresh)
#
# Requirements: Node.js installed (esbuild is fetched
# automatically by npx on first run).
#
# Usage:  bash build.sh
#
# ── js/ FILE ORDER — DO NOT REORDER WITHOUT TESTING ──────────
# The concatenation order below matches the order validated
# against the original monolithic app.js (see handoff notes).
# Because everything here is plain global-scope script (no
# import/export), order mostly doesn't matter — functions are
# hoisted, and nothing outside boot.js runs at parse time. Only
# rule: boot.js must come LAST, since it's the file that
# actually kicks things off (the immediate _initSb()/
# startPrefetch() call and the DOMContentLoaded wiring), and it
# should run only after every init/render function it references
# has been defined.
# ============================================================
set -euo pipefail
cd "$(dirname "$0")"

JS_ORDER="core nav auth home search post-form car-detail notifications follow feed categories leaderboard events members profile garage messages reactions reports awards compare challenges admin theme social boot"

echo "→ Concatenating js/ into app.combined.js..."
> app.combined.js
for m in $JS_ORDER; do
  if [ ! -f "js/$m.js" ]; then
    echo "  ✗ Missing js/$m.js — aborting build."
    exit 1
  fi
  cat "js/$m.js" >> app.combined.js
  echo "" >> app.combined.js
done

echo "→ Minifying JS..."
npx --yes esbuild app.combined.js --minify --charset=utf8 --outfile=app.min.js
npx --yes esbuild db.js            --minify --charset=utf8 --outfile=db.min.js
npx --yes esbuild data.js          --minify --charset=utf8 --outfile=data.min.js

echo "→ Minifying CSS..."
npx --yes esbuild main.css --minify --charset=utf8 --outfile=main.min.css

echo "→ Checking minified JS syntax..."
node --check app.min.js
node --check db.min.js
node --check data.min.js

VERSION=$(date +%Y%m%d%H%M)
echo "→ Bumping cache-bust version to $VERSION ..."
# Replaces every ?v=<digits> on local .min.js / .min.css references
sed -i.bak -E "s/(\.min\.(js|css)\?v=)[0-9]+/\1$VERSION/g" index.html
rm -f index.html.bak

echo "✔ Build complete."
echo "  app.min.js  : $(wc -c < app.min.js) bytes"
echo "  db.min.js   : $(wc -c < db.min.js) bytes"
echo "  data.min.js : $(wc -c < data.min.js) bytes"
echo "  main.min.css: $(wc -c < main.min.css) bytes"
echo "  index.html now points at ?v=$VERSION"
echo
echo "Now commit and push everything, including the .min files"
echo "and the app.combined.js intermediate (or add it to .gitignore"
echo "— it's fully regenerated by this script every run)."
